### ISSUE TITLE
Google fonts don't load

### ISSUE THREAD

**Issue by mpetrovich** [mpetrovich/imagely#7]
When included via external stylesheet, Google fonts don't load:
```html
<link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">
```

It's probably because that linked stylesheet itself references additional external resources:
```css
@font-face {
  …
  src: local('Raleway'), local('Raleway-Regular'), url(https://fonts.gstatic.com/s/raleway/v11/YZaO6llzOP57DpTBv2GnyFKPGs1ZzpMvnHX-7fPOuAc.woff2) format('woff2');
}
```
